rackerlabs/standard-usage-schemas

- archive.wadl
- pom.xml
- add wadl to only allow GET for any /archive/... requests
new wadl (archive.wadl) to supplement repose config changes in this pull request:
https://github.rackspace.com/cloud-integration-ops/puppet-cloudfeeds/pull/301
Can be merged at anytime once tested and reviewed.
> CF-627 Walking Static Archives

- allfeeds.wadl
- bad_message_samples/corexsd/identity-user-acess-event-contenttype-mismatch-with-content.xml
- bad_message_samples/corexsd/identity-user-acess-event-missing-initiator.xml
- bad_message_samples/corexsd/identity-user-acess-event-missing-outcome.xml
- bad_message_samples/corexsd/identity-user-acess-event-missing-requestURL-in-auditdata.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-contenttype-mismatch-with-content.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-missing-initiator.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-missing-outcome.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-missing-requestURL-in-auditdata.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-v1-entry-invalid-content-non-cadf.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-v1-entry-invalid-version.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-v1-entry-unknown-content-type.xml
- core_xsd/uae.xsd
- message_samples/feedsaccess/xml/feeds-user-acess-event-v1-entry.xml
- message_samples/feedsaccess/xml/feeds-user-acess-event-v1-no-region-no-dc.xml
- message_samples/feedsaccess/xml/feeds-user-acess-event-v1-respose.xml
- src/docbkx/api-operations-external.xml
- src/docbkx/api-operations-internal.xml
- wadl/cadf.wadl
- New feed, feeds_access/events feed for feeds UAE
- Added version attribute for auditData
- Updated sample xmls with version attribute
- Updated api-operations with the new feed for docs
- Changes to make region/datacenter required.
> [CF-446] Create new feeds for Cloud Feeds user access events

- bad_message_samples/feedsaccess/feeds-user-acess-event-v1-entry-invalid-content-non-cadf.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-v1-entry-invalid-version.xml
- bad_message_samples/feedsaccess/feeds-user-acess-event-v1-entry-unknown-content-type.xml
- message_samples/feedsaccess/xml/feeds-user-access-event-v1-random-content-response.xml
- message_samples/feedsaccess/xml/feeds-user-access-event-v1-random-content.xml
- wadl/cadf.wadl
Current product events allow content of type text. This PR is to make changes so that feeds_access also allows them.
> CF-447 Changes to allow content other than cadf:event type

- message_samples/nova/json/cloudserversopenstack-nova-server-usage-v1-response.json
- message_samples/nova/xml/cloudserversopenstack-nova-server-usage-v1-response.xml
- src/test/scala/transform-tests.scala
- wadl/atom_hopper_pre.xsl
Remove Nova from being marked ```cloudfeeds:private```. I did not find any trace of Glance eventTypes being marked as ```cloudfeeds:private```
> CF-615: remove nova from being marked as cloudfeeds:private

- src/docbkx/feeds-devguide.xml
Added internal tag to all archiving content. The plan is to redeploy the dev guide without the archiving content to docs external and with the archiving content to docs internal.
> CF-948 added internal tag to all archiving content

- allfeeds.wadl
- src/docbkx/api-operations-internal.xml
Adding the servermill feed in our wadl and doc. Per email from the ServerMill team, this feed can be consumed by customers. But in this PR, I am not adding the externally visible version of this feed, because we do not yet have a schema for it. 
I will add a task in the schema story to make sure the feed is available externally.
> CF-952: add servermill feed

- src/docbkx/samples/archive.json
- src/docbkx/samples/archive.xml
Update documentation's sample archived feeds so they have the correct links.
> CF-721: update links in archive samples

- allfeeds.wadl
- src/docbkx/api-operations-external.xml
Per story, /glace feed is not to be exposed to Observers roles.
> CF-962: remove /glance feed from observer's view

- bad_message_samples/backup/cloudbackup-license-usage-v3-missingServerID.xml
- message_samples/backup/json/cloudbackup-license-agent-usage_snapshot-v3-summary-entry-noServerID.json
- message_samples/backup/xml/cloudbackup-license-agent-usage_snapshot-v3-summary-entry-noServerID.xml
- sample_product_schemas/cloudbackupLicense.xml
This should fix Issue #476 for just the Cloud Backup License usage summary events. This does not fix the Cloud Sites issue mentioned there.
> CF-997: for usage_summary, dont require serverID

- wadl/cadf.wadl
Removing needless sample headings.  This should clean things up for all UAE docs.  The other events' extra blank headings are handled in a later story.
> CF-979 - JSON Samples

- src/test/scala/Xml2JsonSuite.scala
when translating xml empty feed to its JSON equivalent.
> CF-1000: add assert to make sure we don't have empty entry list object

- src/docbkx/feeds-archiving.xml
removed the ";" from all the JSON examples in the archiving section
> CF-1028 remove trailing ; from JSON examples

- product_schema_def/xsl/productSchema-standalone.xsl
This PR adds the following:
When an attribute is a double & has an aggregation function of SUM the following should happen for the usagesummary event:
- type should be double, range facets should be removed.
One side effect, negative values are now allowed.  The only reason I noticed this is that @izrik was using a negative number in a regression tests for sites-metered usagesummary.
I'll have a corresponding PR to fix that test case.
> CF-1003 - Generated UsageSummary schemas don't remove facets for doubles

- allfeeds.wadl
- core_xsd/feedsapi.xsd
- src/test/scala/JsonContentOnlySuite.scala
- wadl/feed.wadl
This PR implements the resourceType "UnvalidatedJsonContentOnly" which has an assert that ensures that atom:content/@type = 'application/json'.  This was implemented for future CADF events to ensure they are always posted as JSON and therefore are never unknowingly transformed by Cloud Feeds between XML & JSON, as the system does for CUF events.
To assist with testing the following feeds were also created:
- unvalidatedjsoncontentonlytest/events - internal testing
- cadftest0/events (up to cadfest9/events) - integration testing by other teams
> CF-1137 - Implement application/json resourceType for generic CADF events

- core_xsd/cadf.xsd
- core_xsd/uae.xsd
Updating the CADF & user access event schemas to allow the following:
- CADF: allow action to be "update/post"
- UAE: tenantId can be empty string
- UAE: userName can be empty string
- UAE: roles can be empty string
These updates were required because I found that the HERP filter has been generating the following events, which have these properties:
**When a user without cloudfeeds:service-admin role attempts to POST to a tenant feed**
```
<cadf:event action="update/post" eventTime="2015-08-05T17:19:07.940+00:00" eventType="activity" id="eb03f19f-7320-4516-905e-d0fbdba43446" outcome="failure" typeURI="http://schemas.dmtf.org/cloud/audit/1.0/event" xsi:schemaLocation="http://schemas.dmtf.org/cloud/audit/1.0/event user-access-cadf.xsd">
<cadf:initiator id="cfeedstestadminrole" …
```
> CF-618 - Feeds UAE env: configure HERP

- product_schema_def/xsd/productSchema.xsd
- src/test/scala/test-base.scala
- src/test/scala/validation-tests.scala
- wadl/feed.wadl
**NOTE:  Don't merge this until https://github.com/rackerlabs/standard-usage-schemas/pull/503 as been merged and ```cloudfeeds:service-observer``` exists in identity & has been assigned to a test role.**
cloudfeeds:service-observer is enabled to be able to read all feeds & entries.  Is not able to POST.
> CF-1037 - Add support for cloudfeeds:service-observer role

- src/main/xsl/xml2json-feeds.xsl
- src/test/resources/event-node-random-ns.xml
- src/test/scala/Xml2JsonSuite.scala
This is to address the exception when someone accidentally messed up the namespace for CADF events and got this error message:
```
An empty sequence is not allowed as the value of variable $version
```
I have added a unit test to cover this. The unit test failed with the above error message without the fix. After applying the fix, the unit test passed successfully.
I will build an RPM next, install on my iNova, and run regression tests.
> CF-1178: fix logic to determine if a node is Rax node

- src/docbkx/feeds-archiving.xml
- src/docbkx/feeds-devguide.xml
removed security="internal" tag from all archiving chapters and sections
> CF 1191 removing security=internal to make archiving public facing

- .gitmodules
- pom.xml
Adding cloudfeeds-nabu submodule to verify that tiamat contains
the latest XSLT generated from SUS.
Adding new tiamat-check profile which:
- diffs the xslt in cloudfeeds-nabu with the corresponding versions in
standard-usage-schemas.  If different, throw an error.  This is done in
the compile step as rm_private_attrs_for_obs.xsl is generated during
the compile step.
> CF-541 - Ensure Tiamat is kept in synch with standard-usage-schema

- sample_product_schemas/servers.xml
This PR basically is to add a couple of private attributes for servers, in specific: huddleID and backstageURL.
I modified sample_product_schemas/servers.xml, I think that's the only place I should do it. If something else is needed, please let me know.
So, we should merge this and then tiamat should fail when running the profile "tiamat-check" since the standard-usage-schema is different to the one in upstream.
After the test, we can revert that merge and forget about that PR.
@shintasmith @usnavi please review
> CF-541: Ensure Tiamat is kept in synch with standard-usage-schema

- .gitignore
- .gitmodules
- pom.xml
- src/main/xsl/striptestfeeds.xsl
- wadl2rst.config.yaml
This PR adds a Maven profile to generate RST files. The process is as follows:
* run wadl-tool's normalized wadl, which combines all our wadls and put them in one file
* run striptestfeeds.xsl to remove functest1 and functest2 from the normalized wadl
* pip install wadl2rst (** I don't like this, but this is they told me this is the only way **)
* run wadl2rst to generate RST files from the stripped off normalized wadl
I had meant to add a copy task to copy the generated RST files to the api-docs/dev-guide/api-operations/methods directory but currently I am running into problems with Maven. If I added that copy task, it suppressed the pip install and running of wadl2rst. I will add that later.
I want to submit this PR soon so that @meker12 and @stanzikratel can run this on their own. …
> CF-1299: add process to convert stripped off normalized wadl to RST files

- product_schema_def/xsl/productSchema-wadl.xsl
The snippet of XSLT in this PR causes the following invalid namespace _0 to be generated in the ```wadl/product.wadl``` file:
```
<method id="getEntryCustomerServiceTenant" name="GET">
<_0:doc xmlns="http://docbook.org/ns/docbook"
xmlns:_0="http://wadl.dev.java.net/2009/02"
xml:lang="EN"
title="Get CustomerService Event">
<para role="shortdesc">This http request fetches one particular event whose ID is listed in the URI.</para>
```
> CF-1299: fix broken wadl xsl

- product_schema_def/xsl/productSchema-wadl.xsl
The generated ```product.wadl``` had incorrect namespace for the ```doc``` element. This is currently how it looks like. The ```doc``` element has the default namespace of docbook.
```
<method id="getEntryCustomerServiceTenant" name="GET">
<doc xmlns="http://docbook.org/ns/docbook"
xml:lang="EN"
title="Get CustomerService Event">
</doc>
...
</method>
```
This causes the DocBook build to skip a lot of content (the attributes descriptions, the XML and JSON samples), because DocBook was looking for a ```doc``` element with wadl namespace.
This PR fixes the above so that it looks like this:
```
<method id="getEntryCustomerServiceTenant" name="GET">
<_0:doc xmlns:outwadl="http://wadl.dev.java.net/2009/02"
xmlns="http://docbook.org/ns/docbook"
xmlns:_0="http://wadl.dev.java.net/2009/02" …
```
> CF-1299: put back the namespace prefix and prefix-to-namespace mapping

- message_samples/jsoncontentonlytest/json/billingaudit-cadf.json
- message_samples/jsoncontentonlytest/xml/billingaudit-cadf.xml
- src/test/scala/sample-messages-tests.scala
Add XML and JSON sample files for Generic CADF.
I had to change the test code a little bit to accommodate the Generic CADF, json only feeds.
> CF-1317: add Generic CADF samples: xml and json

- api-docs/dev-guide/api-operations/methods/get-get-autoscale-event-autoscale-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-big-data-event-bigdata-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-backup-event-backup-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-block-storage-event-cbs-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-database-event-dbaas-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-files-event-files-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-loadbalancers-event-lbaas-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-monitoring-event-monitoring-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-queueus-event-queues-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-servers-(openstack)-event-nova-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloud-servers-event-servers-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-cloudidentity-event-identity-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-rackspacecdn-event-rackspacecdn-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-redhat-enterprise-linux-event-nova-events-tid-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-redhat-enterprise-linux-event-servers-events-tid-entries-id.rst
- product_schema_def/xsl/productSchema-wadl.xsl
This PR is to remove the 409 response code from the wadl for the GET resources. 409 means duplicate entry and it only makes sense in the context of POST requests.
> CF-1299: remove 409 response code from the GET requests

- wadl/cadf.wadl
The cadf.wadl has two sets of 200 response codes and fault codes.  One was updated so that the response and fault codes documentation includes label and description.  This PR updates the second set.
> Update cadf.wadl -== Fix additional fault descriptions

- api-docs/dev-guide/api-operations/methods/get-get-event-id-cadftestid-events-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-event-id-usagetestid-events-entries-id.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-autoscale-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-backup-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-bigdata-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-cadftestid-events.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-cbs-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-dbaas-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-feeds-access-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-files-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-identity-access-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-identity-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-lbaas-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-monitoring-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-nova-access-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-nova-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-queues-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-rackspacecdn-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-servers-events-tid.rst
- api-docs/dev-guide/api-operations/methods/get-get-feed-usagetestid-events.rst
- pom.xml
While investigating the issue #553 that @meker12 reported, I noticed the execution order of the plugin during the Profile ```generate-rst``` was still messed up. The XSLT striptestfeeds.xsl was executed incorrectly before generate normalized wadl. It worked on my source tree because I had a ```normalized/allfeeds.wadl``` already present. The file was not removed during the ```clean``` phase.
This PR solves the 2 issues:
* add ```normalized/allfeeds.wadl``` to be removed during ```clean``` phase
* move the final run of ```wadl2rst``` to the phase ```process-resources```. So the steps and phases are:
* generate normalized wadl => generate-sources
* striptestfeeds.xsl => process-sources
* wadl2rst => process-resources
> CF-1299: fix mvn plugin order issue with generate-rst

- .gitignore
- pom.xml
- product_schema_def/xsl/productSchema-wadl.xsl
- src/xpl/generateWADL.xpl
The changes are:
* generate 2 wadl files: product.wadl (the one for Repose) and productDoc.wadl (the one for wadl2rst)
* change generate-rst profile to swap out productDoc.wadl and product.wadl
* include common.ent in RPM. This file is used in feed.wadl and cadf.wadl. Repose is unhappy if the file is not there.
> CF-1322: fix doc changes that are making Repose unhappy

- bad_message_samples/bigdata/BigData-usage-badAwsDc.xml
- bad_message_samples/bigdata/BigData-usage-badAwsDcRegionMatch.xml
- bad_message_samples/bigdata/BigData-usage-badAwsRegion.xml
- bad_message_samples/misc/RedHat-entry-bad-content.xml
- core_xsd/core.xsd
- core_xsd/xsd10/_1.0Core.xsd
- message_samples/bigdata/json/bigdata-bigdata-hadoop_hdp1_1_aws-usage-v1-entry.json
- message_samples/bigdata/json/bigdata-bigdata-hadoop_hdp1_1_aws-usage-v1-response.json
- message_samples/bigdata/json/bigdata-bigdata-hadoop_hdp2_1_aws-usage-v2-entry.json
- message_samples/bigdata/json/bigdata-bigdata-hadoop_hdp2_1_aws-usage-v2-response.json
- message_samples/bigdata/xml/bigdata-bigdata-hadoop_hdp1_1_aws-usage-v1-entry.xml
- message_samples/bigdata/xml/bigdata-bigdata-hadoop_hdp1_1_aws-usage-v1-response.xml
- message_samples/bigdata/xml/bigdata-bigdata-hadoop_hdp2_1_aws-usage-v2-entry.xml
- message_samples/bigdata/xml/bigdata-bigdata-hadoop_hdp2_1_aws-usage-v2-response.xml
add the aws datacenter / region to the schema (for Cloud Big Data and other future products).
See:  https://jira.rax.io/browse/CF-1329
```
datacenter | region
AWS-US-EAST-1 | AWS-US
AWS-US-WEST-1 | AWS-US
AWS-US-WEST-2 | AWS-US
AWS-EU-WEST-1 | AWS-EU
AWS-EU-CENTRAL-1 | AWS-EU
AWS-AP-SOUTHEAST-1 | AWS-AP
AWS-AP-NORTHEAST-1 | AWS-AP
AWS-AP-SOUTHEAST-2 | AWS-AU
AWS-SA-EAST-1 | AWS-SA
```
> CF-1329: add aws datacenters and regions

- api-docs/dev-guide/_deconst.json
Putting this metadata in place is to support the Edit on Github feature to be added to the docs user interface. The feature is not implemented yet. In the meantime, the metadata has no effect.
> Add metadata to _deconst.json for Edit link
